samples_map: "samples_map.txt" 

PROJ_NAME: "Astrocyte"
RNA_Barcodes: "scRNA_barcodes.csv"
annotations_file: "annotations.txt"
#params 
qc_cmd: "pycistopic_qc_commands.sh"

MALLET_PATH: "/nfs/turbo/umms-thahoang/sherine/tools/Mallet-202108/bin/mallet"
#Thresholds

uniqFrag: 200
minTSS: 0.1
minFrip: 0.0
blacklist: "mm10-blacklist.v2.bed"
ANNOT_BED: "neurog2_gene_annotation.bed"

CHROM_SIZE: "neurog2.chrom.sizes"

adjpval_thr: 0.1
log2fc_thr: 0.25
# Output
out_dir: "scenicOuts"

# Resources
n_cpu: 8


#size of the modified genome
g: 2730873821

#Marker Genes
markers: "mouse_markers.txt"


CELL_TYPES: 
  - MG
  - MGPC
  - Rod
  - Microglia
  - BC
  - Cones
  - AC

#consensus 
combined_bed: "all_combined.bed"
consensus_bed: "final_consensus.bed" 

